### ISSUE TITLE
waitForMongo not defined in services script

### ISSUE THREAD

**Issue by dpatil-fw** [FIWARE/tutorials.Relationships-Linked-Data#10]
The services script in all the 3 tutorials below, refers to **waitForMongo**. This is not defined and hence gives an error while starting.

https://github.com/FIWARE/tutorials.Linked-Data/blob/NGSI-v2/services
https://github.com/FIWARE/tutorials.Working-with-Linked-Data/blob/NGSI-v2/services
https://github.com/FIWARE/tutorials.Relationships-Linked-Data/blob/NGSI-v2/services

Please add the same:

waitForMongo () {
	echo -e "\n⏳ Waiting for \033[1mMongoDB\033[0m to be available\n"
	while ! [ `docker inspect --format='{{.State.Health.Status}}' db-mongo` == "healthy" ]
	do 
		sleep 1
	done
}

**Comment by jason-fox** [comment]
Fixed https://github.com/FIWARE/tutorials.Step-by-Step/commit/b47156f45886e98ed394bccc38a510041c054f3e
